library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - containers
  - servant
  - servant-server
  - text
  - time
  - warp

default-extensions:
  - OverloadedStrings

executables:
  servant-purescript-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -flate-specialise
      - -fspecialise-aggressively
