library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-name-shadowing

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings

executables:
  example-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -flate-specialise
    - -fspecialise-aggressively
